version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      - sudo apt-get update && sudo apt-get install -y terraform
      - terraform -v  
      - echo "Installing jq for JSON processing..."
      - sudo apt-get install -y jq
      - echo "Installing git-secrets..."
      - sudo apt-get install -y git

      # Install git-secrets
      - git clone https://github.com/awslabs/git-secrets.git
      - cd git-secrets && sudo make install && cd ..
  
  build:
    commands:
      - echo "Running Terraform commands..."
      - terraform init
      - echo "Linting Terraform files..."
      - terraform fmt -check
      - terraform validate
      
      # Check for secrets
      - echo "Checking for secrets in the repository..."
      - git secrets --register-aws
      - git secrets --scan-history

      # CodeGuru analysis
      - echo "Running CodeGuru Reviewer..."
      - aws codeguru-reviewer create-code-review --repository-name your-repo-name --branch your-branch-name --name "CodeGuru Review $(date +%Y%m%d-%H%M%S)" --client-request-token $(date +%s)

      - echo "Retrieving db_password from Secrets Manager..."
      - export DB_PASSWORD=$(aws secretsmanager get-secret-value --secret-id teachua-rds-cred --query SecretString --output text | jq -r .password)
      - echo "Applying Terraform with db_password..."
      - terraform apply -auto-approve -var "db_password=$DB_PASSWORD"
      - terraform destroy

  post_build:
    commands:
      - echo "Infrastructure has been successfully deployed on `date`."
